jenkins:
  build: ./docker/jenkins/
  ports:
    - '8080:8080'
    - '50000:50000'
  volumes:
    - '/jenkins-data:/var/jenkins_home'
    - '/var/run/docker.sock:/var/run/docker.sock'
  user: root
  environment:
    - "APP_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
    - "APP_BROKER_URL=amqp://guest:guest@mq:5672//"
    - "APP_CACHE_REDIS_URL=redis://cache:6379/0"
    - "APP_CACHE_TYPE=redis"
    - "APP_CELERY_RESULT_BACKEND=redis://cache:6379/2"
    - "APP_SEARCH_ELASTIC_HOSTS=es:9200"
    - "APP_SECRET_KEY=CHANGE_ME"
    - "APP_SQLALCHEMY_DATABASE_URI=postgresql://cds:cds@db/cds"
  links:
    - cache
    - es
    - mq
    - db
cache:
  image: redis
  ports:
    - "6379:6379"
db:
  image: postgres
  command: postgres
  environment:
    - "POSTGRES_USER=cds"
    - "POSTGRES_PASSWORD=cds"
    - "POSTGRES_DB=cds"
  ports:
    - "5432:5432"
mq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"
es:
  build: ./docker/es/
  ports:
    - "9200:9200"
    - "9300:9300"
